# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 400)
        MainWindow.setMinimumSize(QtCore.QSize(800, 400))
        MainWindow.setMaximumSize(QtCore.QSize(800, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background: #2F8294")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.inputLogin = QtWidgets.QLineEdit(self.page_1)
        self.inputLogin.setGeometry(QtCore.QRect(310, 90, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inputLogin.setFont(font)
        self.inputLogin.setStyleSheet("background: white")
        self.inputLogin.setObjectName("inputLogin")
        self.inputSenha = QtWidgets.QLineEdit(self.page_1)
        self.inputSenha.setGeometry(QtCore.QRect(310, 140, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inputSenha.setFont(font)
        self.inputSenha.setStyleSheet("background: white")
        self.inputSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputSenha.setObjectName("inputSenha")
        self.login_text = QtWidgets.QLabel(self.page_1)
        self.login_text.setGeometry(QtCore.QRect(200, 90, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.login_text.setFont(font)
        self.login_text.setStyleSheet("background: #85EAFF")
        self.login_text.setAlignment(QtCore.Qt.AlignCenter)
        self.login_text.setObjectName("login_text")
        self.senha_text = QtWidgets.QLabel(self.page_1)
        self.senha_text.setGeometry(QtCore.QRect(200, 140, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.senha_text.setFont(font)
        self.senha_text.setStyleSheet("background: #85EAFF")
        self.senha_text.setAlignment(QtCore.Qt.AlignCenter)
        self.senha_text.setObjectName("senha_text")
        self.btn_login = QtWidgets.QPushButton(self.page_1)
        self.btn_login.setGeometry(QtCore.QRect(370, 190, 151, 51))
        self.btn_login.setStyleSheet("background: #945621")
        self.btn_login.setObjectName("btn_login")
        self.btn_cadastro = QtWidgets.QPushButton(self.page_1)
        self.btn_cadastro.setGeometry(QtCore.QRect(210, 190, 151, 51))
        self.btn_cadastro.setStyleSheet("background: #945621")
        self.btn_cadastro.setObjectName("btn_cadastro")
        self.inputError = QtWidgets.QLabel(self.page_1)
        self.inputError.setGeometry(QtCore.QRect(200, 50, 371, 20))
        self.inputError.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inputError.setStyleSheet("color: red")
        self.inputError.setText("")
        self.inputError.setObjectName("inputError")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.nameText = QtWidgets.QLabel(self.page_2)
        self.nameText.setGeometry(QtCore.QRect(0, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nameText.setFont(font)
        self.nameText.setStyleSheet("background: #85EAFF")
        self.nameText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameText.setObjectName("nameText")
        self.inputName = QtWidgets.QLineEdit(self.page_2)
        self.inputName.setGeometry(QtCore.QRect(310, 20, 235, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inputName.setFont(font)
        self.inputName.setStyleSheet("background: white")
        self.inputName.setObjectName("inputName")
        self.emailText = QtWidgets.QLabel(self.page_2)
        self.emailText.setGeometry(QtCore.QRect(0, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.emailText.setFont(font)
        self.emailText.setStyleSheet("background: #85EAFF")
        self.emailText.setObjectName("emailText")
        self.inputEmail = QtWidgets.QLineEdit(self.page_2)
        self.inputEmail.setGeometry(QtCore.QRect(310, 60, 235, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inputEmail.setFont(font)
        self.inputEmail.setStyleSheet("background: white")
        self.inputEmail.setObjectName("inputEmail")
        self.cpfText = QtWidgets.QLabel(self.page_2)
        self.cpfText.setGeometry(QtCore.QRect(0, 100, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cpfText.setFont(font)
        self.cpfText.setStyleSheet("background: #85EAFF")
        self.cpfText.setObjectName("cpfText")
        self.inputCPF = QtWidgets.QLineEdit(self.page_2)
        self.inputCPF.setGeometry(QtCore.QRect(310, 100, 235, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inputCPF.setFont(font)
        self.inputCPF.setStyleSheet("background: white")
        self.inputCPF.setObjectName("inputCPF")
        self.senhaTextCadastro = QtWidgets.QLabel(self.page_2)
        self.senhaTextCadastro.setGeometry(QtCore.QRect(0, 140, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.senhaTextCadastro.setFont(font)
        self.senhaTextCadastro.setStyleSheet("background: #85EAFF")
        self.senhaTextCadastro.setObjectName("senhaTextCadastro")
        self.inputSenhaCadastro = QtWidgets.QLineEdit(self.page_2)
        self.inputSenhaCadastro.setGeometry(QtCore.QRect(310, 140, 235, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inputSenhaCadastro.setFont(font)
        self.inputSenhaCadastro.setStyleSheet("background: white")
        self.inputSenhaCadastro.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputSenhaCadastro.setObjectName("inputSenhaCadastro")
        self.numeroText = QtWidgets.QLabel(self.page_2)
        self.numeroText.setGeometry(QtCore.QRect(0, 270, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.numeroText.setFont(font)
        self.numeroText.setStyleSheet("background: #85EAFF")
        self.numeroText.setObjectName("numeroText")
        self.contaGerador = QtWidgets.QLabel(self.page_2)
        self.contaGerador.setGeometry(QtCore.QRect(310, 270, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.contaGerador.setFont(font)
        self.contaGerador.setStyleSheet("color: #E0AA7C; background: #778899")
        self.contaGerador.setText("")
        self.contaGerador.setObjectName("contaGerador")
        self.buttonIniciar = QtWidgets.QPushButton(self.page_2)
        self.buttonIniciar.setGeometry(QtCore.QRect(0, 350, 162, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIniciar.setFont(font)
        self.buttonIniciar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonIniciar.setStyleSheet("background: #945621")
        self.buttonIniciar.setAutoExclusive(True)
        self.buttonIniciar.setObjectName("buttonIniciar")
        self.buttonCadastro = QtWidgets.QPushButton(self.page_2)
        self.buttonCadastro.setGeometry(QtCore.QRect(350, 200, 137, 37))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.buttonCadastro.setFont(font)
        self.buttonCadastro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonCadastro.setStyleSheet("background: #945621")
        self.buttonCadastro.setAutoExclusive(True)
        self.buttonCadastro.setObjectName("buttonCadastro")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(540, 140, 251, 31))
        self.label_10.setStyleSheet("background: #E0AA7C")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("background: #315F94")
        self.page_5.setObjectName("page_5")
        self.label_6 = QtWidgets.QLabel(self.page_5)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 791, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background:#389413")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_5)
        self.label_7.setGeometry(QtCore.QRect(0, 120, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background: #94B7E0")
        self.label_7.setObjectName("label_7")
        self.inputDeposito = QtWidgets.QLineEdit(self.page_5)
        self.inputDeposito.setGeometry(QtCore.QRect(332, 119, 441, 51))
        self.inputDeposito.setStyleSheet("background: white")
        self.inputDeposito.setObjectName("inputDeposito")
        self.btn_depositar = QtWidgets.QPushButton(self.page_5)
        self.btn_depositar.setGeometry(QtCore.QRect(310, 190, 151, 51))
        self.btn_depositar.setStyleSheet("background: #E05734")
        self.btn_depositar.setObjectName("btn_depositar")
        self.btn_return_page5 = QtWidgets.QPushButton(self.page_5)
        self.btn_return_page5.setGeometry(QtCore.QRect(310, 320, 151, 51))
        self.btn_return_page5.setStyleSheet("background: #E05734")
        self.btn_return_page5.setObjectName("btn_return_page5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label = QtWidgets.QLabel(self.page_4)
        self.label.setGeometry(QtCore.QRect(-4, -1, 791, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: #85EAFF")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_4)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: #85EAFF")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_4)
        self.label_3.setGeometry(QtCore.QRect(0, 140, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: #85EAFF")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(0, 190, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: #85EAFF")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(0, 240, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background: #85EAFF")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.exibir_nome = QtWidgets.QLabel(self.page_4)
        self.exibir_nome.setGeometry(QtCore.QRect(390, 90, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.exibir_nome.setFont(font)
        self.exibir_nome.setStyleSheet("color: #E0AA7C; background: #778899")
        self.exibir_nome.setText("")
        self.exibir_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.exibir_nome.setObjectName("exibir_nome")
        self.exibir_conta = QtWidgets.QLabel(self.page_4)
        self.exibir_conta.setGeometry(QtCore.QRect(390, 140, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.exibir_conta.setFont(font)
        self.exibir_conta.setStyleSheet("color: #E0AA7C; background: #778899")
        self.exibir_conta.setText("")
        self.exibir_conta.setAlignment(QtCore.Qt.AlignCenter)
        self.exibir_conta.setObjectName("exibir_conta")
        self.exibir_cpf = QtWidgets.QLabel(self.page_4)
        self.exibir_cpf.setGeometry(QtCore.QRect(390, 190, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.exibir_cpf.setFont(font)
        self.exibir_cpf.setStyleSheet("color: #E0AA7C; background: #778899")
        self.exibir_cpf.setText("")
        self.exibir_cpf.setAlignment(QtCore.Qt.AlignCenter)
        self.exibir_cpf.setObjectName("exibir_cpf")
        self.exibir_saldo = QtWidgets.QLabel(self.page_4)
        self.exibir_saldo.setGeometry(QtCore.QRect(390, 240, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.exibir_saldo.setFont(font)
        self.exibir_saldo.setStyleSheet("color: #E0AA7C; background: #778899")
        self.exibir_saldo.setText("")
        self.exibir_saldo.setAlignment(QtCore.Qt.AlignCenter)
        self.exibir_saldo.setObjectName("exibir_saldo")
        self.return_button_page_4 = QtWidgets.QPushButton(self.page_4)
        self.return_button_page_4.setGeometry(QtCore.QRect(350, 310, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.return_button_page_4.setFont(font)
        self.return_button_page_4.setStyleSheet("background: #945621")
        self.return_button_page_4.setObjectName("return_button_page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.btn_saldo = QtWidgets.QPushButton(self.page_3)
        self.btn_saldo.setGeometry(QtCore.QRect(290, 10, 181, 61))
        self.btn_saldo.setStyleSheet("background: #696969")
        self.btn_saldo.setObjectName("btn_saldo")
        self.btn_deposito = QtWidgets.QPushButton(self.page_3)
        self.btn_deposito.setGeometry(QtCore.QRect(290, 90, 181, 61))
        self.btn_deposito.setStyleSheet("background: #696969")
        self.btn_deposito.setObjectName("btn_deposito")
        self.btn_tranferencia = QtWidgets.QPushButton(self.page_3)
        self.btn_tranferencia.setGeometry(QtCore.QRect(290, 170, 181, 61))
        self.btn_tranferencia.setStyleSheet("background: #696969")
        self.btn_tranferencia.setObjectName("btn_tranferencia")
        self.btn_return = QtWidgets.QPushButton(self.page_3)
        self.btn_return.setGeometry(QtCore.QRect(290, 300, 181, 61))
        self.btn_return.setStyleSheet("background: #696969")
        self.btn_return.setObjectName("btn_return")
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_text.setText(_translate("MainWindow", "Login"))
        self.senha_text.setText(_translate("MainWindow", "Senha"))
        self.btn_login.setText(_translate("MainWindow", "LOGIN"))
        self.btn_cadastro.setText(_translate("MainWindow", "CADASTRO"))
        self.nameText.setText(_translate("MainWindow", "NOME COMPLETO"))
        self.emailText.setText(_translate("MainWindow", "EMAIL"))
        self.cpfText.setText(_translate("MainWindow", "CPF"))
        self.senhaTextCadastro.setText(_translate("MainWindow", "SENHA"))
        self.numeroText.setText(_translate("MainWindow", "NÚMERO DA CONTA"))
        self.buttonIniciar.setText(_translate("MainWindow", "VOLTAR AO INICIAR"))
        self.buttonCadastro.setText(_translate("MainWindow", "CADASTRAR"))
        self.label_10.setText(_translate("MainWindow", "APENAS 4 DÍGITOS"))
        self.label_6.setText(_translate("MainWindow", "DEPÓSITO"))
        self.label_7.setText(_translate("MainWindow", "VALOR DO DEPÓSITO:    R$"))
        self.btn_depositar.setText(_translate("MainWindow", "DEPOSITAR"))
        self.btn_return_page5.setText(_translate("MainWindow", "RETURN"))
        self.label.setText(_translate("MainWindow", "SALDO"))
        self.label_2.setText(_translate("MainWindow", "NOME COMPLETO:"))
        self.label_3.setText(_translate("MainWindow", "Nº DA CONTA:"))
        self.label_4.setText(_translate("MainWindow", "CPF:"))
        self.label_5.setText(_translate("MainWindow", "SALDO:"))
        self.return_button_page_4.setText(_translate("MainWindow", "RETURN"))
        self.btn_saldo.setText(_translate("MainWindow", "SALDO"))
        self.btn_deposito.setText(_translate("MainWindow", "DEPÓSITO"))
        self.btn_tranferencia.setText(_translate("MainWindow", "TRANSFERÊNCIA"))
        self.btn_return.setText(_translate("MainWindow", "Logout"))
